2021-10-13 13:04:16,540 INFO    MainThread:17624 [wandb_setup.py:_flush():69] setting env: {}
2021-10-13 13:04:16,540 INFO    MainThread:17624 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-13 13:04:16,541 INFO    MainThread:17624 [wandb_init.py:_log_setup():342] Logging user logs to c:\Users\reese\OneDrive\Documents\University\EEE4022S\Workspace\Final-Year-Project\wandb\run-20211013_130416-1ujlrmnv\logs\debug.log
2021-10-13 13:04:16,541 INFO    MainThread:17624 [wandb_init.py:_log_setup():343] Logging internal logs to c:\Users\reese\OneDrive\Documents\University\EEE4022S\Workspace\Final-Year-Project\wandb\run-20211013_130416-1ujlrmnv\logs\debug-internal.log
2021-10-13 13:04:16,542 INFO    MainThread:17624 [wandb_init.py:init():375] calling init triggers
2021-10-13 13:04:16,543 INFO    MainThread:17624 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-10-13 13:04:16,543 INFO    MainThread:17624 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 1kw1r5nw
2021-10-13 13:04:16,544 INFO    MainThread:17624 [wandb_run.py:finish():1271] finishing run rees123/Resnet50 Regression/1kw1r5nw
2021-10-13 13:04:16,737 INFO    MainThread:17624 [jupyter.py:save_history():353] not saving jupyter history
2021-10-13 13:04:16,737 INFO    MainThread:17624 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-10-13 13:04:16,737 INFO    MainThread:17624 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-10-13 13:04:16,737 INFO    MainThread:17624 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-10-13 13:04:16,738 INFO    MainThread:17624 [wandb_run.py:_restore():1543] restore
2021-10-13 13:04:17,356 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 920
  total_bytes: 920
}

2021-10-13 13:04:17,468 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 920
  total_bytes: 920
}

2021-10-13 13:04:17,851 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 920
  total_bytes: 920
}

2021-10-13 13:04:18,694 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 920
  total_bytes: 11490
}

2021-10-13 13:04:18,801 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 920
  total_bytes: 11490
}

2021-10-13 13:04:18,913 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 920
  total_bytes: 11490
}

2021-10-13 13:04:19,025 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 920
  total_bytes: 11490
}

2021-10-13 13:04:19,137 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 920
  total_bytes: 11490
}

2021-10-13 13:04:19,249 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 920
  total_bytes: 11490
}

2021-10-13 13:04:19,359 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11490
  total_bytes: 11490
}

2021-10-13 13:04:19,472 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11490
  total_bytes: 11490
}

2021-10-13 13:04:19,584 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11490
  total_bytes: 11490
}

2021-10-13 13:04:19,696 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11490
  total_bytes: 11490
}

2021-10-13 13:04:19,808 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11490
  total_bytes: 11490
}

2021-10-13 13:04:19,920 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11490
  total_bytes: 11490
}

2021-10-13 13:04:20,033 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11490
  total_bytes: 11490
}

2021-10-13 13:04:20,144 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11490
  total_bytes: 11490
}

2021-10-13 13:04:20,804 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11490
  total_bytes: 11490
}

2021-10-13 13:04:20,919 INFO    MainThread:17624 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 11490
  total_bytes: 11490
}

2021-10-13 13:04:22,084 INFO    MainThread:17624 [wandb_run.py:_show_summary():1848] rendering summary
2021-10-13 13:04:22,086 INFO    MainThread:17624 [wandb_run.py:_show_history():1886] rendering history
2021-10-13 13:04:22,088 INFO    MainThread:17624 [wandb_run.py:_show_files():1915] logging synced files
2021-10-13 13:04:22,102 INFO    MainThread:17624 [wandb_init.py:init():424] starting backend
2021-10-13 13:04:22,102 INFO    MainThread:17624 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-10-13 13:04:22,108 INFO    MainThread:17624 [backend.py:ensure_launched():135] starting backend process...
2021-10-13 13:04:22,437 INFO    MainThread:17624 [backend.py:ensure_launched():139] started backend process with pid: 15948
2021-10-13 13:04:22,438 INFO    MainThread:17624 [wandb_init.py:init():429] backend started and connected
2021-10-13 13:04:22,454 INFO    MainThread:17624 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-10-13 13:04:22,454 INFO    MainThread:17624 [wandb_run.py:_label_probe_notebook():822] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-10-13 13:04:22,455 INFO    MainThread:17624 [wandb_init.py:init():477] updated telemetry
2021-10-13 13:04:22,456 INFO    MainThread:17624 [wandb_init.py:init():500] communicating current version
2021-10-13 13:04:24,143 WARNING MainThread:17624 [wandb_init.py:init():795] interrupted
Traceback (most recent call last):
  File "C:\Users\reese\miniconda3\envs\final-year-project\lib\site-packages\wandb\sdk\wandb_init.py", line 775, in init
    run = wi.init()
  File "C:\Users\reese\miniconda3\envs\final-year-project\lib\site-packages\wandb\sdk\wandb_init.py", line 501, in init
    ret = backend.interface.communicate_check_version(
  File "C:\Users\reese\miniconda3\envs\final-year-project\lib\site-packages\wandb\sdk\interface\interface.py", line 791, in communicate_check_version
    result = self._communicate(rec)
  File "C:\Users\reese\miniconda3\envs\final-year-project\lib\site-packages\wandb\sdk\interface\interface.py", line 539, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\reese\miniconda3\envs\final-year-project\lib\site-packages\wandb\sdk\interface\interface.py", line 77, in get
    is_set = self._object_ready.wait(timeout)
  File "C:\Users\reese\miniconda3\envs\final-year-project\lib\threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Users\reese\miniconda3\envs\final-year-project\lib\threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
